---
dist: xenial
sudo: required

services:
  - docker

language: minimal

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# not yet
#env:
#  - OS=alpine_3.3
#  - OS=alpine_3.4
#  - OS=alpine_3.5
#  - OS=alpine_3.6
#  - OS=alpine_3.7
#  - OS=alpine_3.8
#  - OS=alpine_edge
#  - OS=archlinux_latest
#  - OS=fedora_23
#  - OS=fedora_24
#  - OS=fedora_25
#  - OS=fedora_26
#  - OS=fedora_27
#  - OS=fedora_28
#  - OS=fedora_29
#  - OS=fedora_30
#  - OS=debian_jessie
#  - OS=debian_stretch
#  - OS=debian_buster
#  - OS=ubuntu_trusty
#  - OS=ubuntu_xenial
#  - OS=ubuntu_bionic

env:
  - OS=alpine_3.10
  - OS=alpine_3.9
  - OS=centos_7

script:
  - docker build -t quay.io/andrewrothstein/docker-ansible:$OS -f Dockerfile.$OS .
#  - docker login -u $DCB_TARGET_QUAY_IO_USER -p $DCB_TARGET_QUAY_IO_PWD
#  - docker push quay.io/andrewrothstein/docker-ansible:$OS
