---
dist: xenial
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman
  - sudo mkdir -p /etc/containers

language: minimal

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine DOTVER=3.11 DASHVER=3_11
  - OS=alpine DOTVER=3.12 DASHVER=3_12
  - OS=alpine DOTVER=3.10 DASHVER=3_10
  - OS=alpine DOTVER=edge DASHVER=edge
  - OS=archlinux DOTVER=latest DASHVER=latest
  - OS=centos DOTVER=7 DASHVER=7
  - OS=centos DOTVER=8 DASHVER=8
  - OS=debian DOTVER=bullseye DASHVER=bullseye
  - OS=debian DOTVER=buster DASHVER=buster
  - OS=debian DOTVER=stretch DASHVER=stretch
  - OS=fedora DOTVER=31 DASHVER=31
  - OS=fedora DOTVER=32 DASHVER=32
  - OS=gentoo DOTVER=latest DASHVER=latest
  - OS=ubi8 DOTVER=8.0 DASHVER=8_0
  - OS=ubi8 DOTVER=8.1 DASHVER=8_1
  - OS=ubi8 DOTVER=8.2 DASHVER=8_2
  - OS=ubuntu DOTVER=bionic DASHVER=bionic
  - OS=ubuntu DOTVER=focal DASHVER=focal
  - OS=ubuntu DOTVER=xenial DASHVER=xenial

before_script:
  - podman login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" quay.io

script:
  - ./build.sh $OS $DOTVER $DASHVER
  - podman push quay.io/andrewrothstein/docker-ansible:${OS}_${DOTVER}
