---
dist: focal
sudo: required
before_install:
  - . /etc/os-release
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
  - sudo apt-key add - < Release.key
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install buildah

language: minimal

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=alpine DOTVER=3.13 DASHVER=3_13
  - OS=alpine DOTVER=3.14 DASHVER=3_14
  - OS=alpine DOTVER=edge DASHVER=edge
  - OS=archlinux DOTVER=latest DASHVER=latest
#  - OS=centos DOTVER=7 DASHVER=7
  - OS=centos DOTVER=8 DASHVER=8
  - OS=debian DOTVER=bullseye DASHVER=bullseye
  - OS=debian DOTVER=buster DASHVER=buster
#  - OS=debian DOTVER=stretch DASHVER=stretch
  - OS=fedora DOTVER=34 DASHVER=34
  - OS=fedora DOTVER=35 DASHVER=35
#  - OS=ubi8 DOTVER=8.2 DASHVER=8_2
#  - OS=ubi8 DOTVER=8.3 DASHVER=8_3
  - OS=ubuntu DOTVER=bionic DASHVER=bionic
  - OS=ubuntu DOTVER=focal DASHVER=focal
#  - OS=ubuntu DOTVER=xenial DASHVER=xenial

script:
  - sudo buildah login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  - sudo buildah login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
  - ./build.sh $OS $DOTVER $DASHVER
  - sudo buildah push quay.io/andrewrothstein/docker-ansible:${OS}_${DOTVER}
