---
version: '3'
dotenv:
  - .env
tasks:
  build:
    vars:
      os: '{{ .os | default "ubuntu" }}'
      os_ver: '{{ .os_ver | default "noble" }}'
      platforms: '{{ .platforms | default "linux/amd64,linux/arm64" }}'
    cmds:
      - >-
        dagger call
        build
        --os={{ .os | quote }}
        --os-ver={{ .os_ver | quote }}
        --platforms={{ .platforms | quote }}
  publish:
    vars:
      os: '{{ .os | default "ubuntu" }}'
      os_ver: '{{ .os_ver | default "noble" }}'
      dockerhub_username: '{{ .dockerhub_username | default "${DOCKERHUB_USERNAME}" }}'
      dockerhub_password: '{{ .dockerhub_password | default "env:DOCKERHUB_PASSWORD" }}'
      ghcr_username: '{{ .ghcr_username | default "${GITHUB_ACTOR}" }}'
      ghcr_password: '{{ .ghcr_password | default "env:GITHUB_TOKEN" }}'
      platforms: '{{ .platforms | default "linux/amd64,linux/arm64" }}'
    desc: Publish the Docker image to Docker Hub and GitHub Container Registry
    cmds:
      - >-
        dagger call
        publish
        --os={{ .os | quote }}
        --os-ver={{ .os_ver | quote }}
        --dockerhub-username={{ .dockerhub_username | quote }}
        --dockerhub-password={{ .dockerhub_password | quote }}
        --ghcr-username={{ .ghcr_username | quote }}
        --ghcr-password={{ .ghcr_password | quote }}
        --platforms={{ .platforms | quote }}
