#!/bin/sh
apk update \
    && apk upgrade \
    && apk add \
           shadow \
           python3 \
           python3-dev \
           build-base \
           libffi-dev \
           openssl-dev \
           wget \
           ca-certificates \
    && wget https://bootstrap.pypa.io/get-pip.py -O /usr/local/bin/get-pip.py \
    && python3 /usr/local/bin/get-pip.py \
    && pip install urllib3 ansible==2.7.10 \
    && apk del \
           build-base \
           libffi-dev \
           openssl-dev \
    && rm -rf /var/cache/apk/*
