---
name: dcb
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - alpine_317
          - alpine_318
          - alpine_edge
          - archlinux_latest
          - debian_bookworm
          - debian_bullseye
          - fedora_37
          - fedora_38
          - rockylinux_8
          - rockylinux_9
          - ubuntu_focal
          - ubuntu_jammy
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" docker.io
      - run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
      - run: docker login -u "${{ github.actor }}" -p "${{ github.token }}" ghcr.io
      - run: docker buildx bake --pull --push ${{ matrix.target }}
