---
name: dcb
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - TARGET: alpine_317
            OS: alpine
            OS_VER: 3.17
          - TARGET: alpine_318
            OS: alpine
            OS_VER: 3.18
          - TARGET: alpine_edge
            OS: alpine
            OS_VER: edge
          - TARGET: archlinux_latest
            OS: archlinux
            OS_VER: latest
          - TARGET: debian_bookworm
            OS: debian
            OS_VER: bookworm
          - TARGET: debian_bullseye
            OS: debian
            OS_VER: bullseye
          - TARGET: fedora_37
            OS: fedora
            OS_VER: 37
          - TARGET: fedora_38
            OS: fedora
            OS_VER: 38
          - TARGET: rockylinux_8
            OS: rockylinux
            OS_VER: 8
          - TARGET: rockylinux_9
            OS: rockylinux
            OS_VER: 9
          - TARGET: ubuntu_focal
            OS: ubuntu
            OS_VER: focal
          - TARGET: ubuntu_jammy
            OS: ubuntu
            OS_VER: jammy
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - uses: docker/login-action@v2
        with:
          registry: quay.io
          username: "${{ secrets.QUAY_USERNAME }}"
          password: "${{ secrets.QUAY_PASSWORD }}"
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - uses: docker/bake-action@v3
        with:
          pull: true
          push: true
          target: "${{ matrix.distro.TARGET }}"
          env:
            OS: "${{ matrix.distro.OS }}"
            OS_VER: "${{ matrix.distro.OS_VER }}"
