---
name: image-bake-and-scan
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      distro: ${{ steps.read-matrix.outputs.distro }}
    steps:
      - uses: actions/checkout@v4
      - name: read platform-matrix-v1.json
        id: read-matrix
        run: echo "distro=$(jq -cr '@json' < platform-matrix-v1.json)" >> $GITHUB_OUTPUT
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJSON(needs.prepare-matrix.outputs.distro) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dagger
        uses: dagger/dagger-for-github@8.0.0
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          verb: call
          args: >-
            publish
            --os=${{ matrix.distro.OS }}
            --os-ver=${{ matrix.distro.OS_VER }}
            --upstream-org=${{ matrix.distro.UPSTREAM_ORG || 'library' }}
            --upstream-os=${{ matrix.distro.UPSTREAM_OS || matrix.distro.OS }}
            --upstream-os-ver=${{ matrix.distro.UPSTREAM_OS_VER || matrix.distro.OS_VER }}
            --dockerhub-username=${{ vars.DOCKERHUB_USERNAME }}
            --dockerhub-password=env:DOCKERHUB_PASSWORD
            --ghcr-username=${{ github.actor }}
            --ghcr-password=env:GITHUB_TOKEN
