---
name: dcb
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - OS: alpine
            OS_VER: 3.17
          - OS: alpine
            OS_VER: 3.18
          - OS: alpine
            OS_VER: edge
          - OS: archlinux
            OS_VER: latest
          - OS: debian
            OS_VER: bookworm
          - OS: debian
            OS_VER: bullseye
          - OS: fedora
            OS_VER: 37
          - OS: fedora
            OS_VER: 38
          - OS: rockylinux
            OS_VER: 8
          - OS: rockylinux
            OS_VER: 9
          - OS: ubuntu
            OS_VER: focal
          - OS: ubuntu
            OS_VER: jammy
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: "${{ vars.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - uses: docker/bake-action@v3
        env:
          OS: "${{ matrix.distro.OS }}"
          OS_VER: "${{ matrix.distro.OS_VER }}"
          SHA: "${{ env.GITHUB_SHA }}"
        with:
          pull: true
          push: true
