---
name: image-bake-and-scan
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - OS: alpine
            OS_VER: 3.17
          - OS: alpine
            OS_VER: 3.18
          - OS: alpine
            OS_VER: edge
          - OS: archlinux
            OS_VER: latest
          - OS: debian
            OS_VER: bookworm
          - OS: debian
            OS_VER: bullseye
          - OS: fedora
            OS_VER: 38
          - OS: fedora
            OS_VER: 39
          - OS: rockylinux
            OS_VER: 8
          - OS: rockylinux
            OS_VER: 9
          - OS: ubuntu
            OS_VER: focal
          - OS: ubuntu
            OS_VER: jammy
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: "${{ vars.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - uses: docker/bake-action@v4
        env:
          OS: "${{ matrix.distro.OS }}"
          OS_VER: "${{ matrix.distro.OS_VER }}"
          SHA: "${{ github.sha }}"
        with:
          pull: true
          push: true
      - uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}:0.0.0-${{ matrix.distro.OS }}.${{ matrix.distro.OS_VER }}"
          severity: 'CRITICAL,HIGH'
          format: sarif
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
