---
name: test-role
on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
  pull_request:
jobs:
  test-role-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Clone k9s ansible role
        uses: actions/checkout@v4
        with:
          repository: andrewrothstein/ansible-k9s
          path: ansible-k9s

      - name: Test the test-role function on Ubuntu AMD64
        uses: dagger/dagger-for-github@8.0.0
        with:
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          args: >-
            call
            test-role
            --os=ubuntu
            --os-ver=noble
            --platforms=linux/amd64
            --role-name=k9s
            --role-dir=./ansible-k9s

  test-role-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Clone k9s ansible role
        uses: actions/checkout@v4
        with:
          repository: andrewrothstein/ansible-k9s
          path: ansible-k9s

      - name: Test the test-role function on Ubuntu ARM64
        uses: dagger/dagger-for-github@8.0.0
        with:
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          args: >-
            call
            test-role
            --os=ubuntu
            --os-ver=noble
            --platforms=linux/arm64
            --role-name=k9s
            --role-dir=./ansible-k9s
